oat-sa/extension-tao-advanced-search

- model/Metadata/Service/ClassMetadataSearcher.php
- tests/Unit/Metadata/Service/ClassMetadataSearcherTest.php
> Release 1.0.1

- .github/workflows/conventional_commits_check.yml
- .github/workflows/release_tao_extension.yml
> Release 1.0.2

- README.md
- scripts/tools/IndexClassMetadata.sh
- scripts/tools/IndexDeliveryResults.sh
- scripts/tools/IndexPopulator.php
- scripts/tools/IndexPopulator.sh
- scripts/tools/IndexResources.sh
Avoid big elastic search request size
https://oat-sa.atlassian.net/browse/ADF-256
> Avoid big elastic search request size

- README.md
- scripts/tools/IndexClassMetadata.sh
- scripts/tools/IndexDeliveryResults.sh
- scripts/tools/IndexPopulator.php
- scripts/tools/IndexPopulator.sh
- scripts/tools/IndexResources.sh
> Release 1.0.3

- README.md
- model/Metadata/Normalizer/MetadataNormalizer.php
- model/Metadata/Repository/ClassUriCachedRepository.php
- model/Metadata/Repository/ClassUriRepository.php
- model/Metadata/Repository/ClassUriRepositoryInterface.php
- model/Metadata/Service/MetadataResultSearcher.php
- model/Metadata/Task/MetadataMigrationTask.php
- scripts/tools/CacheWarmup.php
- scripts/tools/CacheWarmup.sh
- scripts/tools/IndexClassMetadata.sh
- scripts/tools/IndexDeliveryResults.sh
- scripts/tools/IndexPopulator.sh
- tests/Unit/Metadata/Normalizer/MetadataNormalizerTest.php
- tests/Unit/Metadata/Repository/ClassUriCachedRepositoryTest.php
- tests/Unit/Metadata/Repository/ClassUriRepositoryTest.php
- tests/Unit/Metadata/Service/MetadataResultSearcherTest.php
- tests/Unit/Metadata/Task/MetadataMigrationTaskTest.php
> Release 1.1.0

- README.md
- composer.json
- manifest.php
- migrations/Version202106011320101488_taoAdvancedSearch.php
- scripts/install/RegisterTaskQueueServices.php
- scripts/uninstall/UnRegisterTaskQueueServices.php
https://oat-sa.atlassian.net/browse/ADF-305
_TODO_
> Feature/adf 305/separate tasks for indx

- README.md
- composer.json
- manifest.php
- migrations/Version202106011320101488_taoAdvancedSearch.php
- scripts/install/RegisterTaskQueueServices.php
- scripts/uninstall/UnRegisterTaskQueueServices.php
> Release 1.2.0

- model/Metadata/Listener/ClassDeletionListener.php
- model/Metadata/Service/ClassMetadataSearcher.php
https://oat-sa.atlassian.net/browse/AUT-698
Unit tests will be part of https://github.com/oat-sa/extension-tao-advanced-search/pull/30 together with bigger changes
> fix: broken service retrival fixed

- model/Metadata/Listener/ClassDeletionListener.php
- model/Metadata/Service/ClassMetadataSearcher.php
> Release 1.2.1

- model/Index/Service/ResultIndexer.php
- tests/Unit/Index/Service/ResultIndexerTest.php
https://oat-sa.atlassian.net/browse/ADF-270
> fix: prevents putting meaningless tasks into the queue

- model/Index/Service/ResultIndexer.php
- tests/Unit/Index/Service/ResultIndexerTest.php
> Release 1.3.1

- migrations/Version202107021653331488_taoAdvancedSearch.php
- model/Metadata/Factory/ClassPathFactory.php
- model/Metadata/Listener/MetadataInheritanceListener.php
- model/Metadata/Normalizer/MetadataNormalizer.php
- model/Metadata/Service/ClassMetadataSearcher.php
- scripts/install/RegisterEvents.php
- tests/Unit/Metadata/Factory/ClassPathFactoryTest.php
- tests/Unit/Metadata/Listener/MetadataInheritanceListenerTest.php
- tests/Unit/Metadata/Normalizer/MetadataNormalizerTest.php
- tests/Unit/Metadata/Service/ClassMetadataSearcherTest.php
> Release 1.4.0

- README.md
- scripts/tools/GarbageCollector.sh
- scripts/tools/ResourceIndexGarbageCollector.php
> Release 1.5.0

- README.md
- composer.json
- migrations/Version202108120848511488_taoAdvancedSearch.php
- model/Metadata/Listener/ClassMovedListener.php
- scripts/install/RegisterEvents.php
- tests/Unit/Metadata/Listener/ClassMovedListenerTest.php
https://oat-sa.atlassian.net/browse/ADF-519
depends on https://github.com/oat-sa/tao-core/pull/3052
> chore: new listner for indexation searh criterias at moved classes

- README.md
- model/Resource/Service/SyncResourceResultIndexer.php
- scripts/tools/IndexMissingRecords.php
> Release 1.5.3

- README.md
- manifest.php
- model/Metadata/Normalizer/MetadataNormalizer.php
- model/Metadata/ServiceProvider/MetadataServiceProvider.php
- model/Metadata/Specification/PropertyAllowedSpecification.php
- tests/Unit/Metadata/Normalizer/MetadataNormalizerTest.php
- tests/Unit/Metadata/Specification/PropertyAllowedSpecificationTest.php
Remove certain system properties from criteria filter.
TODO
https://oat-sa.atlassian.net/browse/ADF-620
> feat: remove system properties from indexation

- README.md
- manifest.php
- model/Metadata/Normalizer/MetadataNormalizer.php
- model/Metadata/ServiceProvider/MetadataServiceProvider.php
- model/Metadata/Specification/PropertyAllowedSpecification.php
- tests/Unit/Metadata/Normalizer/MetadataNormalizerTest.php
- tests/Unit/Metadata/Specification/PropertyAllowedSpecificationTest.php
> Release 1.7.0

- composer.json
Update lib to improve reindexation 
https://oat-sa.atlassian.net/browse/ADF-863
> chore: update lib-tao-elasticsearch

- composer.json
> Release 1.7.1

- model/Metadata/Service/ClassMetadataSearcher.php
- tests/Unit/Metadata/Service/ClassMetadataSearcherTest.php
> Release 1.7.2

- composer.json
> Release 1.7.3

- composer.json
> Release 1.7.4

- model/Index/Service/ResultIndexer.php
- model/Index/Service/SyncResultIndexer.php
- model/Resource/Service/SyncResourceResultIndexer.php
- tests/Unit/Index/Service/ResultIndexerTest.php
**Associated Jira issue:** [ADF-568](https://oat-sa.atlassian.net/browse/ADF-568)
Related merge requests:
- https://github.com/oat-sa/tao-core/pull/3424
> feat: Improve logging for index operations

- model/Index/Service/ResultIndexer.php
- model/Index/Service/SyncResultIndexer.php
- model/Resource/Service/SyncResourceResultIndexer.php
- tests/Unit/Index/Service/ResultIndexerTest.php
> Release 1.8.0

- composer.json
**Associated Jira issue:** [ADF-568](https://oat-sa.atlassian.net/browse/ADF-568).
> chore: Bump required versions to improve Advanced Search logging

- composer.json
> Release 1.8.1

- config/index.conf.php
- migrations/Version202209141256261488_taoAdvancedSearch.php
- model/Metadata/Service/AdvancedSearchSearchSettingsService.php
- model/Metadata/Service/AdvancedSearchSettingsService.php
- model/Metadata/ServiceProvider/MetadataServiceProvider.php
- scripts/tools/Activate.php
- tests/Unit/Metadata/Service/AdvancedSearchSettingsServiceTest.php
https://oat-sa.atlassian.net/browse/ADF-1192
> feat: provide selectable columns as search settings

- migrations/Version202209081525261488_taoAdvancedSearch.php
Reverts oat-sa/extension-tao-advanced-search#71
> Revert "Add check of service existence before retrieving its options"

- migrations/Version202209081525261488_taoAdvancedSearch.php
> Release 1.9.1

- model/SearchEngine/Service/IndexPrefixer.php
- scripts/tools/Activate.php
- tests/Unit/SearchEngine/Service/IndexPrefixerTest.php
> Release 1.9.2

- model/SearchEngine/Driver/Elasticsearch/ElasticSearchIndexer.php
> Release 1.9.3

- .github/workflows/continuous-integration.yaml
- composer.json
- manifest.php
- migrations/Version202209271256261488_taoAdvancedSearch.php
- model/Metadata/Service/ListMetadataSynchonizer.php
- model/Metadata/Service/ListSavedEventListener.php
- model/Metadata/ServiceProvider/MetadataServiceProvider.php
- model/Resource/Service/ResourceIndexer.php
- model/Resource/ServiceProvider/ResourceServiceProvider.php
- model/Resource/Task/ResourceMigrationTask.php
- scripts/install/RegisterEvents.php
- tests/Unit/Metadata/Service/ListSavedEventListenerTest.php
- tests/Unit/Resource/Service/ResourceIndexerTest.php
https://oat-sa.atlassian.net/browse/ADF-1198
- When a remote list os local list gets updated we need to reindex all the resources that are using properties from this list
> Feature/adf 1198/repopulate indeces on list update

- .github/workflows/continuous-integration.yaml
- README.md
Update doc and use latest continuous integration
> chore: update doc and use latest continuous integration

- .github/workflows/continuous-integration.yaml
- README.md
> Release 1.9.4

- composer.json
- config/deliveries.conf.php
- config/items.conf.php
- config/tests.conf.php
- manifest.php
- model/Index/Service/AdvancedSearchIndexDocumentBuilder.php
- model/Index/Service/ResultIndexer.php
- model/Index/ServiceProvider/IndexServiceProvider.php
- model/Resource/Service/SyncResourceResultIndexer.php
- tests/Unit/Index/Service/AdvancedSearchIndexDocumentBuilderTest.php
- tests/Unit/Resource/Service/SyncResourceResultIndexerTest.php
> Release 1.11.0

- composer.json
- model/Index/Service/AdvancedSearchIndexDocumentBuilder.php
- tests/Unit/Index/Service/AdvancedSearchIndexDocumentBuilderTest.php
> chore: fix typo

- composer.json
- model/Index/Service/AdvancedSearchIndexDocumentBuilder.php
- tests/Unit/Index/Service/AdvancedSearchIndexDocumentBuilderTest.php
> Release 1.11.1

- README.md
- config/tests.conf.php
- manifest.php
- migrations/Version202307251344000003_taoAdvancedSearch.php
- model/Index/Service/AdvancedSearchIndexDocumentBuilder.php
- model/Index/Service/SyncResultIndexer.php
- model/Test/Normalizer/TestNormalizer.php
- model/Test/ServiceProvider/TestServiceProvider.php
- scripts/tools/IndexMigration.php
- tests/Unit/Index/Service/AdvancedSearchIndexDocumentBuilderTest.php
- tests/Unit/Test/Normalizer/TestNormalizerTest.php
https://oat-sa.atlassian.net/browse/AUT-3163
Add a new properties for test called `test_qti_strucuture` that stores the QTI Json saved by our QTI SDK and can be queries lated on Dynamic API
1) Update index
```
php tao/scripts/taoUpdate.php
```
2) Create a test with several test parts and sections 
3) Save the test and check ElasticSearch storage
Example of outcome: 
```json
{
"took" : 1002,
"timed_out" : false,
"_shards" : {
"total" : 1,
"successful" : 1,
"skipped" : 0,
"failed" : 0
},
"hits" : {
"total" : {
"value" : 1,
"relation" : "eq"
},
"max_score" : 0.6931471,
"hits" : [
{
"_index" : "gabriel-tests",
"_type" : "_doc",
"_id" : "https://test-tao-deploy.docker.localhost/ontologies/tao.rdf#i62068b4d275cd18558b34aec5e26a90db",
"_score" : 0.6931471,
"_source" : {
"label" : [ …
```
> feat: Persist test QTI structure to be used later by DynamicAPI

- README.md
- config/tests.conf.php
- manifest.php
- migrations/Version202307251344000003_taoAdvancedSearch.php
- model/Index/Service/AdvancedSearchIndexDocumentBuilder.php
- model/Index/Service/SyncResultIndexer.php
- model/Test/Normalizer/TestNormalizer.php
- model/Test/ServiceProvider/TestServiceProvider.php
- scripts/tools/IndexMigration.php
- tests/Unit/Index/Service/AdvancedSearchIndexDocumentBuilderTest.php
- tests/Unit/Test/Normalizer/TestNormalizerTest.php
> Release 1.13.0

- .github/workflows/release_tao_extension.yml
updated automatic SemVer release action with new bot user to bypass branch protection rule in place
> fix: updated automatic SemVer release action

- composer.json
- model/DeliveryResult/Normalizer/DeliveryResultNormalizer.php
- model/DeliveryResult/Repository/DeliveryResultRepository.php
- model/DeliveryResult/Service/DeliveryResultSearcher.php
- model/Resource/Service/ResourceSearcher.php
- tests/Unit/DeliveryResult/Repository/DeliveryResultRepositoryTest.php
- tests/Unit/DeliveryResult/Service/DeliveryResultSearcherTest.php
Complete backport of v1.14.0 on top of previously backport v1.13.2.1. Needed for OATSD-2845
> Backport/oatsd 2845/v1.14.0 to v1.13.2.2

- scripts/tools/CacheWarmup.sh
- scripts/tools/GarbageCollector.sh
- scripts/tools/IndexClassMetadata.sh
- scripts/tools/IndexClassResources.sh
- scripts/tools/IndexDeliveryResults.sh
- scripts/tools/IndexPopulator.sh
- scripts/tools/IndexResources.sh
* Shell scripts changes to use `#!/bin/sh` instead of `#!/bin/bash`
[ADF-1667]: https://oat-sa.atlassian.net/browse/ADF-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix] Use SH instead of BASH

- model/SearchEngine/Driver/Elasticsearch/ElasticSearch.php
Set proper index with prefixes if we have them
> fix: set proper index name with prefix

- model/Index/Service/AdvancedSearchIndexDocumentBuilder.php
- tests/Unit/Index/Service/AdvancedSearchIndexDocumentBuilderTest.php
Introduce performance improvement from https://github.com/oat-sa/extension-tao-advanced-search/pull/125 - Backporting https://github.com/oat-sa/extension-tao-advanced-search/releases/tag/v1.18.1 to https://github.com/oat-sa/extension-tao-advanced-search/releases/tag/v1.16.2
- https://oat-sa.atlassian.net/browse/ADF-1761
- https://oat-sa.atlassian.net/browse/PISA25-700
> Fix/release v1.16.2

- model/Resource/Service/ItemClassRelationService.php
- model/Resource/Service/ItemRelationsService.php
- model/Resource/ServiceProvider/ResourceServiceProvider.php
- tests/Unit/Resource/Service/ItemClassRelationServiceTest.php
- tests/Unit/Resource/Service/ItemRelationsServiceTest.php
This will create new feature flag that will enable item relation check on item or item class deletion action
> Feat/adf 1856/create feature flag to enable item relation check

- model/SearchEngine/Driver/Elasticsearch/ElasticSearch.php
Fix issue when during creating, prefix was ignored
> fix: update index creating script

- model/DeliveryResult/Normalizer/DeliveryResultNormalizer.php
https://oat-sa.atlassian.net/browse/ADF-1449
> fix: use propoer import to class
